language: go

go:
  - "1.11.x"

dist: xenial

services:
  - mongodb

env:
  - EKADASHI_MONGO_URL=mongodb://localhost:27017
  - GO111MODULE=on
  -
script:
  - make mod
  - make lint
  - make test
  - make build

before_script:
  - sleep 20
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
