// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Session struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	LastModifiedDate     int64    `protobuf:"varint,2,opt,name=LastModifiedDate,json=lastModifiedDate,proto3" json:"LastModifiedDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Session) GetLastModifiedDate() int64 {
	if m != nil {
		return m.LastModifiedDate
	}
	return 0
}

type User struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Session              *Session `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *Response) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "grpc.Session")
	proto.RegisterType((*User)(nil), "grpc.User")
	proto.RegisterType((*Response)(nil), "grpc.Response")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x34, 0x1a, 0xfb, 0xf1, 0x5a, 0xa5, 0x3c, 0x3c, 0x94, 0x9e, 0x4a, 0x2e, 0x16, 0x95, 0x1c,
	0x22, 0xf8, 0x0b, 0x14, 0x04, 0x2b, 0xc2, 0x06, 0x7f, 0xc0, 0xea, 0x3e, 0xd3, 0xa5, 0x25, 0x1b,
	0xde, 0x5b, 0xed, 0x4f, 0xf1, 0xef, 0x4a, 0x76, 0xd3, 0x1c, 0x3c, 0xe8, 0x6d, 0x66, 0x77, 0x66,
	0x98, 0x79, 0x30, 0x15, 0xe2, 0x2f, 0xe2, 0xbc, 0x61, 0xe7, 0x1d, 0xa6, 0x15, 0x37, 0xef, 0xd9,
	0x13, 0x0c, 0x4b, 0x12, 0xb1, 0xae, 0xc6, 0x0b, 0x38, 0xf5, 0x6e, 0x4b, 0xf5, 0x3c, 0x59, 0x26,
	0xab, 0xb1, 0x8a, 0x04, 0xaf, 0x60, 0xb6, 0xd6, 0xe2, 0x9f, 0x9d, 0xb1, 0x1f, 0x96, 0xcc, 0xbd,
	0xf6, 0x34, 0x3f, 0x5e, 0x26, 0xab, 0x13, 0x35, 0xdb, 0xfd, 0x7a, 0xcf, 0xee, 0x20, 0x7d, 0x15,
	0x62, 0x44, 0x48, 0x3f, 0x85, 0xb8, 0x0b, 0x0a, 0x18, 0x17, 0x30, 0x6a, 0xb4, 0xc8, 0xde, 0xb1,
	0x09, 0xfe, 0xb1, 0xea, 0x79, 0xf6, 0x02, 0x23, 0x45, 0xd2, 0xb8, 0x5a, 0xa8, 0xd5, 0x71, 0x87,
	0x3b, 0x7f, 0xcf, 0xf1, 0x12, 0x86, 0x12, 0xcb, 0x86, 0x88, 0x49, 0x71, 0x96, 0xb7, 0x23, 0xf2,
	0x6e, 0x81, 0x3a, 0xfc, 0x16, 0xdf, 0x09, 0x0c, 0xca, 0x30, 0x16, 0x0b, 0xc0, 0x47, 0x5d, 0x9b,
	0x1d, 0x29, 0xaa, 0xac, 0x78, 0xd6, 0xbe, 0xdd, 0x0a, 0xd1, 0xd8, 0xb6, 0x5d, 0x9c, 0x47, 0x7c,
	0x68, 0x90, 0x1d, 0xe1, 0x35, 0x4c, 0xa2, 0x67, 0xed, 0x2a, 0xfb, 0x9f, 0xf8, 0x06, 0xa6, 0xe5,
	0xc6, 0xed, 0x1f, 0xb6, 0xda, 0x68, 0xd9, 0xd8, 0xbf, 0xd5, 0x6f, 0x83, 0x70, 0xfc, 0xdb, 0x9f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0xd0, 0x93, 0x2e, 0x8c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	HandleRegistration(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
	HandleLogin(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
	ShowEkadashi(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) HandleRegistration(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc.Server/HandleRegistration", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) HandleLogin(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc.Server/HandleLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) ShowEkadashi(ctx context.Context, in *User, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpc.Server/ShowEkadashi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	HandleRegistration(context.Context, *User) (*Response, error)
	HandleLogin(context.Context, *User) (*Response, error)
	ShowEkadashi(context.Context, *User) (*Response, error)
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_HandleRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).HandleRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Server/HandleRegistration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).HandleRegistration(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_HandleLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).HandleLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Server/HandleLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).HandleLogin(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_ShowEkadashi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).ShowEkadashi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Server/ShowEkadashi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).ShowEkadashi(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleRegistration",
			Handler:    _Server_HandleRegistration_Handler,
		},
		{
			MethodName: "HandleLogin",
			Handler:    _Server_HandleLogin_Handler,
		},
		{
			MethodName: "ShowEkadashi",
			Handler:    _Server_ShowEkadashi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
